### ISSUE TITLE
Panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by FZambia** [govend/govend#33] opened 2016-03-09 10:20 UTC
Hello, just got a panic running govend:

```
govend golang.org/x/crypto
```

Panic:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/govend/govend/imports/filters.projectImportPath(0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/imports/filters/filters.go:144 +0x399
github.com/govend/govend/imports/filters.Local(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/imports/filters/filters.go:81 +0x3e
github.com/govend/govend/imports.Scan(0xc8204c0f80, 0x1a, 0xc820507760, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/imports/scan.go:119 +0x9d6
github.com/govend/govend/deps.Vend(0xc8200f7000, 0x1, 0x1, 0x9160e8, 0x4, 0xc820507b08, 0x0, 0x0, 0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/deps/vend.go:185 +0xfae
main.glob.func1(0xb6c640, 0xc8200f6f20, 0x1, 0x1)
        /home/fz/environments/gopath/src/github.com/govend/govend/main.go:114 +0xa8c
github.com/govend/govend/vendor/github.com/spf13/cobra.(*Command).execute(0xb6c640, 0xc82000a190, 0x1, 0x1, 0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/vendor/github.com/spf13/cobra/command.go:569 +0x869
github.com/govend/govend/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb6c640, 0xb6c640, 0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/vendor/github.com/spf13/cobra/command.go:656 +0x56b
github.com/govend/govend/vendor/github.com/spf13/cobra.(*Command).Execute(0xb6c640, 0x0, 0x0)
        /home/fz/environments/gopath/src/github.com/govend/govend/vendor/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
        /home/fz/environments/gopath/src/github.com/govend/govend/main.go:132 +0x49d
```

**Comment by jackspirou** [comment] 2016-03-09 13:31
@FZambia it appears the slice reporting that out of bounds error is due to this line: https://github.com/govend/govend/blob/master/imports/filters/filters.go#L144

Are you running the `govend` command outside of your $GOPATH `src`? `govend` is meant to be ran in the repository root of your project.

When I run `govend -v golang.org/x/crypto` in a project repo root directory inside of my `$GOPATH` I am unable to reproduce the error above.  Instead I get:

```
→ govend -v golang.org/x/crypto 
golang.org/x/crypto
```

If the above doesn't help, can you give me some more info, such as your `$GOPQTH` the `pwd` of where your currently running `govend` and the version of Go you have installed? Also you may want to try `go get -u github.com/govend/govend` to ensure you have the current version.

Thanks!

**Comment by FZambia** [comment] 2016-03-09 20:06
hello @jackspirou, thanksfor response. From my home computer everything worked fine! I got this panic at work on Centos 6 – will try to reproduce this and provide details tomorrow. I think I launched it from $GOPATH and used latest version but will be sure tomorrow:)

**Comment by FZambia** [comment] 2016-03-10 09:25
@jackspirou - so it seems that I used it in wrong way, but not because outside of $GOPATH:

$GOPATH: `/home/fz/environments/gopath`
pwd: `/home/fz/environments/gopath/src/mrmon`

When I ran `govend golang.org/x/crypto` just now - everything works as expected.

But yesterday my Go bin dir was not in PATH so I ran this `../../bin/govend golang.org/x/crypto` - and this resulted in panic.

**Comment by jackspirou** [comment] 2016-03-10 14:39
@FZambia thanks for the info.  You need to be in the `src` directory of your `$GOPATH`.  Sorry, I inferred that above and didn't make it clear.  I have added `"/src"` to the error message now, so you don't get a panic error :) 

https://github.com/govend/govend/blob/master/deps/vendorable.go#L35

I'll close this issue, but please let me know if you have any other thoughts or feedback.

**Closed by jackspirou** 2016-03-10 14:39 UTC
